config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'cocktails#index'

  resources :cocktails, only: [:create, :index, :show, :new] do
    resources :doses, only: [:create, :new]
    resources :reviews, only: [:create, :new]
  end
  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_one_attached :photo
  has_many :reviews, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :ingredient, :scope => [:cocktail]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :cocktail
  validates :content, :presence => {:message => 'cannot be blank'}
  validates :rating, :inclusion => { :in => 0..5, :message => 'The rating should be between 0 and 5' }
  validates :rating, :presence => {:message => 'cannot be blank'}
  validates :rating, :presence => { :message => 'should be a number'}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
# Will raise ActiveModel::ForbiddenAttributesError

class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    @cocktail.save
    redirect_to cocktail_path(@cocktail)
  end

  def new
    @cocktail = Cocktail.new
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  before_action :find_cocktail, except: :destroy

  def new
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    @dose.save
    redirect_to cocktail_path(@cocktail)
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def find_cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @review = Review.new(review_params)
    # we need `review_id` to associate review with corresponding cocktail
    @cocktail = Cocktail.find(params[:cocktail_id])
    @review.cocktail = @cocktail
    @review.save
    redirect_to cocktail_path(@cocktail)
  end

  def new
    @review = Review.new
    @cocktail = Cocktail.find(params[:cocktail_id])
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/cocktails/index.html.erb
<div class="menu-top">
  <h1>All Creations</h1>
</div>
<p class="dropdown_sentence">
  <span id="banner-typed-text"></span>
</p>
  <div class="mx-4">

  <div class="align">
    <div class="row">
      <% @cocktails.each do |cocktail| %>
        <div class="col-6 col-md-4 col-lg-3 mx-0">
          <%= link_to (cocktail) do %>
            <div class="card-category my-3" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%= cl_image_path(cocktail.photo.key) %>)">
            <%= cocktail.name %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <%= button_to "Create a new cocktail", new_cocktail_path(@cocktails),
    class: "btn-flat", :method => :get %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h1 class="menu-top">Add a creation to the menu</h1>

<div class="container">
    <%= simple_form_for(@cocktail)  do |f| %>
    <div >
    <%= f.input :name %>
    <%= f.input :photo, as: :file, label: "Add a picture for your cocktail!" %>
    <%= f.submit"Submit Cocktail", class: "btn-flat w-100"%>
    </div>
  <% end %>
</div>

app/views/cocktails/show.html.erb
  <h2 class="menu-top"><%= @cocktail.name %></h2>
 <div class="mx-4">
  <div class="align">
    <% @cocktail.doses.each do |dose| %>
      <p>
        <%= dose.ingredient.name %> | <%= dose.description %>
        <%= button_to "Delete this dose", dose_path(dose),
        :class => "btn-small", :method => :delete %>
      </p>
      <hr>
    <% end %>
  <div class="container">
    <div class="item">
      <%= link_to "Add a new ingredient", new_cocktail_dose_path(@cocktail),
      :class => "btn-flat", :method => :get %>
    </div>
    <div>
      <%= link_to 'Leave a review', new_cocktail_review_path(@cocktail),
      :class => "btn-flat" %>
    </div>
  </div>
  </div>
</div>

  <div class="review-block">
    <h2 class="menu-top"><%="Reviews"%></h2>
      <div class="reviews">
      <% @cocktail.reviews.each do |r| %>
          <div class="review-category">
            <%= "★" * r.rating   %> <br><%= r.content %>
          </div>
        <% end %>
      </div>
  </div>

app/views/doses/new.html.erb
<div class="container">
  <div class="align">
    <h1 class="menu-top">Add ingredients to your creation</h1>
    <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.association :ingredient %>
      <%= f.input :description %>
      <%= f.button :submit , class: "btn-flat"%>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <link href="https://fonts.googleapis.com/css2?family=Cabin+Condensed:wght@600&family=Quicksand:wght@400;600&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
  </head>

  <body>
  <div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <%= link_to cocktails_path(@cocktails), class: "navbar-brand" do %>
    <%= image_tag("mixozax.png") %>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <img src=""./assets/images/mixozax">


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to "Home", cocktails_path(@cocktails),  class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "New Creation", new_cocktail_path(@cocktails) , class: "nav-link"%>
      </li>
    </ul>
  </div>
</div>


    <%= yield %>
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/louisdemof"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/cocktails/"><i class="fab fa-instagram"></i></a>
  </div>
  <div class="footer-copyright">
    This website was made with <i class="fas fa-heart"></i> by Zax
  </div>
</div>
  </body>
</html>

app/views/reviews/new.html.erb
<div class="container">
  <div class="align">
    <h1 class="menu-top">Add a review</h1>
    <%= simple_form_for [@cocktail, @review] do |f| %>
      <%= f.input :content %>
      <%= f.input :rating %>
      <%= f.button :submit , class: "btn-flat"%>
    <% end %>
  </div>
</div>